language: bash

sudo: required

services:
  - docker

env:
#   Debian
  - OS_SUITE=stretch NGINX_SUITE=mainline VERSION=1.13.8
  - OS_SUITE=stretch NGINX_SUITE=stable VERSION=1.12.2

#   Ubuntu
  - OS_SUITE=xenial NGINX_SUITE=mainline VERSION=1.13.8
  - OS_SUITE=xenial NGINX_SUITE=stable VERSION=1.12.2

before_install:
  - export DOCKER_COMPOSE_VERSION=1.18.0
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - env | sort
  - cd "$NGINX_SUITE/$OS_SUITE"
  - image="xutl/nginx:${VERSION}-${OS_SUITE}"

script:
  - travis_retry docker build -t "$image" .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login --username="${DOCKER_REGISTRY_USER}" --password="${DOCKER_REGISTRY_PASSWORD}";
      docker push $image;
      docker tag $image xutl/nginx:${VERSION};
      docker push xutl/nginx:${VERSION};
      if [[ "${VERSION}" == "1.13.8" && "${OS_SUITE}" == "xenial" ]]; then
        docker tag $image xutl/nginx:1.13;
        docker push xutl/nginx:1.13;
        docker tag $image xutl/nginx:latest;
        docker push xutl/nginx:latest;
        docker tag $image xutl/nginx:mainline;
        docker push xutl/nginx:mainline;
      fi;
      if [[ "${VERSION}" == "1.12.2" && "${OS_SUITE}" == "xenial" ]]; then
        docker tag $image xutl/nginx:stable;
        docker push xutl/nginx:stable;
        docker tag $image xutl/nginx:1.12;
        docker push xutl/nginx:1.12;
      fi;
    fi;

# vim:set et ts=2 sw=2:
